from . import res_company
from . import res_users
from . import stock_config
from . import product_uom
from . import product_category
from . import product_template
from . import product_product
from . import stock_location
from . import stock_warehouse
from . import stock_production_lot
from . import stock_picking_type
from . import stock_picking
from . import stock_move
from . import stock_inventory