{
    "name" : "Mejoras en Proceso de Almacen/Logistica",
    'version': '1.0.0.0',
    "author" : "Carlos López Mite",
    "website": "https://blaze-otp.com",
    "category" : "Warehouse",
    "description": """Mejoras en Proceso de Almacen/Logistica""",
    "depends" : [
        'base',
        'product',
        'stock',
        'odoo_utils',
        'uom',
    ],
    "init" : [],
    'qweb' : [],
    'demo': [],
    'test': [],
    "data": [
        'data/module_category_data.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        #'data/system_data_init.xml',
        'report/report_stock_inventory.xml',
        'views/menu_root.xml',
        'views/stock_config_view.xml',
        'views/product_price_history_view.xml',
        'views/product_uom_view.xml',
        'views/product_template_view.xml',
        'views/product_product_view.xml',
        'views/stock_picking_view.xml',
        'views/stock_picking_type_view.xml',
        'views/stock_picking_type_dashboard_view.xml',
        'views/stock_move_view.xml',
        'views/stock_move_line_view.xml',
        'views/stock_quant_view.xml',
        'views/stock_warehouse_view.xml',
        'views/stock_warehouse_orderpoint_view.xml',
        'views/stock_location_view.xml',
        'views/stock_inventory_view.xml',
        'views/procurement_rule_view.xml',
        'views/procurement_group_view.xml',
    ],
    "installable": True,
    "auto_install": True,
}
