{
    "name": "Mejoras en Proceso de Contabilidad",
    'version': '1.0.0.1',
    "author": "Carlos Lopez Mite",
    "website": "https://blaze-otp.com",
    "category": "Accounting",
    "description": """Mejoras en Proceso de Contabilidad""",
    "depends": [
        "base",
        "account",
        "payment",
        "product",
        "odoo_utils",
    ],
    'data': [
        'data/module_category_data.xml',
        'security/groups.xml',
        'data/report_paperformat.xml',
        'views/menu_root.xml',
        'report/report_account_move.xml',
        'wizard/wizard_change_tax_products.xml',
        'wizard/wizard_account_invoice_change.xml',
        'views/account_incoterms_view.xml',
        'views/account_config_view.xml',
        'views/account_move_view.xml',
        'views/account_move_line_view.xml',
        'views/account_analytic_account_view.xml',
        'views/account_analytic_line_view.xml',
        'views/account_bank_statement_view.xml',
        'views/account_invoice_view.xml',
        'views/account_journal_view.xml',
        'views/account_journal_dashboard_view.xml',
        'views/account_invoice_report_view.xml',
        'views/account_payment_view.xml',
        'views/ir_actions_view.xml',
    ],
    'installable': True,
    'auto_install': True,
}
